### ISSUE TITLE
Turinio licencija

### ISSUE THREAD

**Issue by rimas-kudelis** [embar-/opensuse.lt#4]
@embar- , pasižiūrėk, ar gera licencija nurodyta footeryje. Aš jame palikau tą patį tekstą, kurį naudojau lietuvybė.lt, bet nežinau, kaip jūs norite savo turinį licencijuoti. Jeigu licencija tinka ir patinka, gal norėsi nusikopijuoti ir [LICENSE failą](https://github.com/lietuvybe-lt/lietuvybe.lt/blob/main/LICENSE).

Taip paga pagalvok dėl [README](https://github.com/lietuvybe-lt/lietuvybe.lt/blob/main/README.md), nes dabar tuščias. :)

**Comment by embar-** [comment]
Ačiū, nusikopijavau tą pačią licenciją - tinka
